name: kvizz
description: "A real time multiplayer quiz playing app"

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  http: ^1.0.0
  flutter_dotenv: ^5.1.0
  flutter_lints: ^5.0.0
  provider: ^6.1.5
  file_picker: ^10.2.0
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Kvizz.png
    - config.env
    - assets/lottie/
